version: 0.2
phases:
  install:
    commands:
      - echo "Installing AWS CDK"
      - npm install -g aws-cdk
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Synthesizing the CDK stack"
      - cdk synth
artifacts:
  base-directory: cdk.out
  files:
    - CdkAssignment8910233Stack.template.json
